//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OMR_GESTION_DE_DATOS.Modelos
{
    using System;
    using System.Collections.Generic;
    
    public partial class titleview
    {
        public string title { get; set; }
        public Nullable<byte> au_ord { get; set; }
        public string au_lname { get; set; }
        public Nullable<decimal> price { get; set; }
        public Nullable<int> ytd_sales { get; set; }
        public string pub_id { get; set; }
    }
}
